//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int sale_id { get; set; }
        public int buyer_id { get; set; }
        public int product_id { get; set; }
        public System.DateTime sale_date { get; set; }
        public decimal sale_price { get; set; }
        public string goods_status { get; set; }
        public int buy_amount { get; set; }
    }
}
